### ISSUE TITLE
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: Index 4 out of bounds for length 4

### ISSUE THREAD

**Issue by en660552** [skadistats/clarity-examples#47]
I'am trying to run skadistats.clarity.examples.particles.Main and i got error. Why does it occur?

Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: Index 4 out of bounds for length 4
	at skadistats.clarity.model.s2.S2LongFieldPathFormat.down(S2LongFieldPathFormat.java:23)
	at skadistats.clarity.model.s2.S2LongModifiableFieldPath.down(S2LongModifiableFieldPath.java:19)
	at skadistats.clarity.decoder.s2.FieldOpType$8.execute(FieldOpType.java:55)
	at skadistats.clarity.decoder.s2.S2FieldReader.readFields(S2FieldReader.java:56)
	at skadistats.clarity.decoder.s2.S2FieldReader.readFields(S2FieldReader.java:14)
	at skadistats.clarity.processor.entities.Entities.getBaseline(Entities.java:486)
	at skadistats.clarity.processor.entities.Entities.processEntityCreate(Entities.java:372)
	at skadistats.clarity.processor.entities.Entities.onPacketEntities(Entities.java:317)
	at skadistats.clarity.event.AbstractInvocationPoint.invoke(AbstractInvocationPoint.java:86)
	at skadistats.clarity.event.Event.raise(Event.java:41)
	at skadistats.clarity.processor.reader.InputSourceProcessor.processEmbedded(InputSourceProcessor.java:247)
	at skadistats.clarity.event.AbstractInvocationPoint.invoke(AbstractInvocationPoint.java:86)
	at skadistats.clarity.event.Event.raise(Event.java:41)
	at skadistats.clarity.processor.reader.InputSourceProcessor.processSource(InputSourceProcessor.java:174)
	at skadistats.clarity.event.AbstractInvocationPoint.invoke(AbstractInvocationPoint.java:86)
	at skadistats.clarity.event.Event.raise(Event.java:41)
	at skadistats.clarity.processor.runner.AbstractFileRunner.initAndRunWith(AbstractFileRunner.java:39)
	at skadistats.clarity.processor.runner.SimpleRunner.runWith(SimpleRunner.java:33)
	at skadistats.clarity.examples.particles.Main.run(Main.java:173)
	at skadistats.clarity.examples.particles.Main.main(Main.java:179)

**Comment by spheenik** [comment]
Looks like a corrupt replay. Can you supply it?

**Comment by spheenik** [comment]
Damn, scratch that. Looks like the version of clarity that you use is too old.
Which version?

**Comment by en660552** [comment]
You right. I'am used 2.5 version. After upgrading to 2.6 everything works fine. Thenk you!
