### ISSUE TITLE
Exception in thread "main" skadistats.clarity.ClarityException: cannot determine last tick before engine type is known

### ISSUE THREAD

**Issue by egyptianmessi** [skadistats/clarity-examples#60]
I'm trying to run the matchend example using `gradlew.bat matchendRun --args "my-replay.dem" ` and I'm getting the following error:

```
Exception in thread "main" skadistats.clarity.ClarityException: cannot determine last tick before engine type is known
        at skadistats.clarity.source.Source.determineLastTick(Source.java:178)
        at skadistats.clarity.source.Source.getLastTick(Source.java:194)
        at skadistats.clarity.processor.runner.ControllableRunner.getLastTick(ControllableRunner.java:347)
        at skadistats.clarity.examples.matchend.Main.<init>(Main.java:35)
        at skadistats.clarity.examples.matchend.Main.main(Main.java:24)
<=========----> 75% EXECUTING [3s]
```

I have not changed any code from the example. Other examples are working for me, such as the "info" example.

Any help would be much appreciated!

**Comment by spheenik** [comment]
You found a bug!
Thank you for reporting.
I released `clarity 3.0.3` which fixes this.
Just pull `clarity-examples`, it should then reference 3.0.3 and the code should work.
