### ISSUE TITLE
Can't run any example

### ISSUE THREAD

**Issue by thurd** [skadistats/clarity-examples#62]
I've cloned the repo. I've studied the Readme. I've successfully built allchatPackage into a single jar (using command "gradlew.bat allchatPackage"). But when I run the single JAR with command "java -jar build\libs\allchat.jar 7627973973.dem", where 7627973973.dem is my demo file I get:

SLF4J: A SLF4J service provider failed to instantiate:
org.slf4j.spi.SLF4JServiceProvider: Error accessing configuration file
SLF4J: No SLF4J providers were found.
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See https://www.slf4j.org/codes.html#noProviders for further details.
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at com.needhamsoftware.unojar.Boot.main(Boot.java:233)
Caused by: java.lang.ExceptionInInitializerError
        at skadistats.clarity.processor.runner.ExecutionModel.requireProvider(ExecutionModel.java:108)
        at skadistats.clarity.processor.runner.ExecutionModel.requireEventListener(ExecutionModel.java:144)
        at skadistats.clarity.processor.runner.ExecutionModel.requireProcessorClass(ExecutionModel.java:78)
        at skadistats.clarity.processor.runner.ExecutionModel.addProcessor(ExecutionModel.java:48)
        at skadistats.clarity.processor.runner.AbstractRunner.addProcessorsToModel(AbstractRunner.java:40)
        at skadistats.clarity.processor.runner.AbstractRunner.addProcessorsToModel(AbstractRunner.java:38)
        at skadistats.clarity.processor.runner.AbstractRunner.createExecutionModel(AbstractRunner.java:31)
        at skadistats.clarity.processor.runner.AbstractRunner.initWithProcessors(AbstractRunner.java:46)
        at skadistats.clarity.processor.runner.AbstractFileRunner.initAndRunWith(AbstractFileRunner.java:36)
        at skadistats.clarity.processor.runner.SimpleRunner.runWith(SimpleRunner.java:33)
        at skadistats.clarity.examples.allchat.Main.main(Main.java:23)
        ... 5 more
Caused by: java.lang.RuntimeException: ClassIndex: Cannot read class index
        at org.atteo.classindex.ClassIndex.readIndexFile(ClassIndex.java:394)
        at org.atteo.classindex.ClassIndex.getAnnotatedNames(ClassIndex.java:305)
        at org.atteo.classindex.ClassIndex.getAnnotated(ClassIndex.java:265)
        at org.atteo.classindex.ClassIndex.getAnnotated(ClassIndex.java:249)
        at skadistats.clarity.event.UsagePoints.<clinit>(UsagePoints.java:24)
        ... 16 more
Caused by: java.nio.file.NoSuchFileException: C:\Users\Tymon\Documents\YouTube%20Channel\Dota%202\replayparser\clarity-examples\build\libs\allchat.jar
        at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:85)
        at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
        at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
        at java.base/sun.nio.fs.WindowsFileAttributeViews$Basic.readAttributes(WindowsFileAttributeViews.java:53)
        at java.base/sun.nio.fs.WindowsFileAttributeViews$Basic.readAttributes(WindowsFileAttributeViews.java:38)
        at java.base/sun.nio.fs.WindowsFileSystemProvider.readAttributes(WindowsFileSystemProvider.java:199)
        at java.base/java.nio.file.Files.readAttributes(Files.java:1851)
        at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1429)
        at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:718)
        at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:252)
        at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:181)
        at java.base/java.util.jar.JarFile.<init>(JarFile.java:346)
        at java.base/java.util.jar.JarFile.<init>(JarFile.java:317)
        at java.base/java.util.jar.JarFile.<init>(JarFile.java:256)
        at com.needhamsoftware.unojar.UnoJarFile.<init>(UnoJarFile.java:34)
        at com.needhamsoftware.unojar.UnoJarURLConnection.connect(UnoJarURLConnection.java:49)
        at com.needhamsoftware.unojar.JarClassLoader$FileURLFactory$1.openConnection(JarClassLoader.java:890)
        at java.base/java.net.URL.openConnection(URL.java:1094)
        at java.base/java.net.URL.openStream(URL.java:1161)
        at org.atteo.classindex.ClassIndex.readIndexFile(ClassIndex.java:378)
        ... 20 more

**Comment by thurd** [comment]
Turns out my path was too long and probably "spaces" in names caused additional issues. Possibly could be fixed by some additional checks or like me, transfer the whole thing to a new directory.
